// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ktb8hJzYv8lga1llwFSTkhqP3xEh2Qc',
    appId: '1:600860420045:web:d762d98db57c79cef70684',
    messagingSenderId: '600860420045',
    projectId: 'chat-app-3777f',
    authDomain: 'chat-app-3777f.firebaseapp.com',
    storageBucket: 'chat-app-3777f.appspot.com',
    measurementId: 'G-GZ0YJ1KCYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzz7ibVk3cn5vziz-GHS_cFbybnTRKJi0',
    appId: '1:600860420045:android:7d7f85250847facdf70684',
    messagingSenderId: '600860420045',
    projectId: 'chat-app-3777f',
    storageBucket: 'chat-app-3777f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwW3sbPHAOyLyZcV4JZHPi_4Xmvg0MaY',
    appId: '1:600860420045:ios:8dd30ef8eaa5fbe3f70684',
    messagingSenderId: '600860420045',
    projectId: 'chat-app-3777f',
    storageBucket: 'chat-app-3777f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiwW3sbPHAOyLyZcV4JZHPi_4Xmvg0MaY',
    appId: '1:600860420045:ios:ce14ba0c417c28f1f70684',
    messagingSenderId: '600860420045',
    projectId: 'chat-app-3777f',
    storageBucket: 'chat-app-3777f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
